import { ThemeProvider } from "@mui/material";
import type { AppProps } from "next/app";
import Head from "next/head";
import { useState } from "react";
import BasicDrawer from "../components/BasicDrawer";
import Navbar from "../components/Navbar";
import { darkTheme } from "../utils/theme";

export default function App({ Component, pageProps }: AppProps) {
	const [theme, setTheme] = useState(darkTheme);
	const [drawerOpen, setDrawerOpen] = useState(false);

	return (
		<ThemeProvider theme={theme}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar
				theme={theme}
				setTheme={setTheme}
				drawerOpen={drawerOpen}
				setDrawerOpen={setDrawerOpen}
			/>
			<BasicDrawer drawerOpen={drawerOpen} setDrawerOpen={setDrawerOpen} />
			<Component {...pageProps} />
		</ThemeProvider>
	);
}
